#
# html
#

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

#
# python
#

[[plugins]]
repo = "jmcantrell/vim-virtualenv"
on_ft = ["python", "python3"]

#
# php
#

[[plugins]]
repo = 'joonty/vdebug'
on_ft = 'php'
hook_source = '''
let g:vdebug_force_ascii = 1

let g:vdebug_options = {
\    "break_on_open" : 0
\}

let g:vdebug_keymap = {
\    "run" : ",v5",
\    "run_to_cursor" : ",v9",
\    "step_over" : ",v2",
\    "step_into" : ",v3",
\    "step_out" : ",v4",
\    "close" : ",v6",
\    "detach" : ",v7",
\    "set_breakpoint" : ",v10",
\    "get_context" : ",v11",
\    "eval_under_cursor" : ",v12",
\    "eval_visual" : ",v13",
\}
'''

#
# golang
#

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''

augroup go
  autocmd!
  autocmd FileType go nmap <leader>t  <Plug>(go-test-func)
  autocmd FileType go nmap <leader>a  <Plug>(go-alternate-edit)
  autocmd FileType go nmap <leader>av  <Plug>(go-alternate-vertical)
  autocmd FileType go nmap <leader>as  <Plug>(go-alternate-split)
augroup END
let g:go_list_type = "quickfix"
let g:go_fmt_command = "goimports"

let g:go_def_mapping_enabled = 0
let g:go_doc_keywordprg_enabled = 0

let g:go_def_mode='gopls'
let g:go_info_mode='gopls'

let g:go_auto_type_info = 1

" highlight
let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_function_calls  = 1
let g:go_highlight_function_parameters = 1
let g:go_highlight_functions = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_types = 1
let g:go_highlight_variable_declarations = 1
let g:go_highlight_variable_assignments = 1

" tagbar settings for golang
let g:tagbar_type_go = {
	\ 'ctagstype' : 'go',
	\ 'kinds'     : [
		\ 'p:package',
		\ 'i:imports:1',
		\ 'n:interfaces',
		\ 't:types',
		\ 'c:constants',
		\ 'v:variables',
		\ 'w:fields',
		\ 'e:embedded',
		\ 'm:methods',
		\ 'r:constructor',
		\ 'f:functions'
	\ ],
	\ 'sro' : '.',
	\ 'kind2scope' : {
		\ 't' : 'ctype',
		\ 'n' : 'ntype'
	\ },
	\ 'scope2kind' : {
		\ 'ctype' : 't',
		\ 'ntype' : 'n'
	\ },
	\ 'ctagsbin'  : 'gotags',
	\ 'ctagsargs' : '-sort -silent'
\ }
'''

[[plugins]]
repo = 'buoto/gotests-vim'
on_ft = 'go'
