[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = 'source ~/.vim/rc/plugins/coc.rc.vim'

[[plugins]]
repo = 'josa42/coc-go'
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'neoclide/coc-yaml'
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'neoclide/coc-vetur'
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'neoclide/coc-css'
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'neoclide/coc-json'
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'neoclide/coc-html'
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'neoclide/coc-tabnine'
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'neoclide/coc-snippets'
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'josa42/coc-sh'
build = 'yarn install --frozen-lockfile'

[[plugins]]
repo = 'fannheyward/coc-sql'
build = 'yarn install --frozen-lockfile'
