[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/rc/plugins/lightline.rc.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
let g:ctrlp_map = ',p'

let g:ctrlp_max_files = 0
let g:ctrlp_lazy_update = 10
let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden --ignore .git --ignore .svn --ignore .hg --ignore .DS_Store --ignore "**/*.pyc" -g ""'
let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }
'''

[[plugins]]
repo = 'FelikZ/ctrlp-py-matcher'
depends = 'ctrlp.vim'

[[plugins]]
repo = 'sgur/vim-lazygutter'

[[plugins]]
repo = 'kana/vim-fakeclip'

[[plugins]]
repo = 'fuenor/qfixhowm'
hook_add = '''
let QFixHowm_Key = 'g'

let howm_dir             = '~/howm'
let howm_filename        = '%Y/%m/%Y-%m-%d-%H%M%S.md'
let howm_fileencoding    = 'utf-8'
let howm_fileformat      = 'unix'

let QFixHowm_FileType = 'markdown'
let QFixHowm_Title = '#:'
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
nmap <silent> <Leader>r <Plug>(quickrun)

let g:quickrun_config = {
\    "_" : {
\       'runner' : 'vimproc'
\    },
\   "markdown" : {
\       'outputter/buffer/close_on_empty' : 1,
\       'command' : 'open',
\       'cmdopt'  : '-a',
\       'args'    : 'Marked',
\       'exec'    : '%c %o %a %s',
\    },
\   "watchdogs_checker/_" : {
\       "runner/vimproc/updatetime" : 50,
\   },
\}
'''

[[plugins]]
repo = "jceb/vim-hier"

[[plugins]]
repo = "osyo-manga/shabadou.vim"

[[plugins]]
repo = "dannyob/quickfixstatus"

[[plugins]]
repo = "osyo-manga/vim-watchdogs"
depends = [
    'vim-hier',
    'quickfixstatus',
    'shabadou.vim',
    'vim-quickrun'
]
hook_add = '''
let g:watchdogs_check_BufWritePost_enable = 1
let g:watchdogs_check_CursorHold_enable = 1
'''
hook_post_source = '''
call watchdogs#setup(g:quickrun_config)
'''

[[plugins]]
repo = 'soramugi/auto-ctags.vim'
on_ft = ["php", "c", "cpp", "python", "javascript"]
depends = 'unite.vim'
hook_source = '''
let project_root = unite#util#path2project_directory(getcwd())
let g:auto_ctags = 1
let g:auto_ctags_directory_list = [project_root.'/.git', project_root.'/.svn']
let g:auto_ctags_tags_args = '--tag-relative --append=yes --recurse=yes --sort=yes --links=no'
let g:auto_ctags_filetype_mode = 1
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'LeafCage/yankround.vim'
on_map = [['nxo', '<Plug>']]
hook_add = '''
nmap p <Plug>(yankround-p)
xmap p <Plug>(yankround-p)
nmap P <Plug>(yankround-P)
nmap gp <Plug>(yankround-gp)
xmap gp <Plug>(yankround-gp)
nmap gP <Plug>(yankround-gP)
nmap <C-p> <Plug>(yankround-prev)
nmap <C-n> <Plug>(yankround-next)
'''
hook_source = '''
let g:yankround_dir = "~/.vim/.backup/yankround"
let g:yankround_use_region_hl = 1
let g:yankround_max_history = 100
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
