[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_add = 'source ~/.vim/rc/plugins/unite.rc.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = [['n', '<Plug>']]
hook_add = '''
let g:EasyMotion_do_mapping = 0
let g:EasyMotion_keys = 'abcdefghijklmnopqrstuvwxyz'
let g:EasyMotion_smartcase = 1

nmap <Leader>e <Plug>(easymotion-overwin-w)
nmap <Leader>s <Plug>(easymotion-overwin-f2)
'''

[[plugins]]
repo = 'AndrewRadev/switch.vim'
on_cmd = ['Switch']
hook_add = 'nnoremap - :Switch<cr>'

[[plugins]]
repo = 't9md/vim-textmanip'
on_map = [['nxo', '<Plug>']]
hook_add = '''
xmap <S-j> <Plug>(textmanip-move-down)
xmap <S-k> <Plug>(textmanip-move-up)
xmap <S-h> <Plug>(textmanip-move-left)
xmap <S-l> <Plug>(textmanip-move-right)

map <Space>d <Plug>(textmanip-duplicate-down)
nmap <Space>d <Plug>(textmanip-duplicate-down)
xmap <Space>D <Plug>(textmanip-duplicate-up)
nmap <Space>D <Plug>(textmanip-duplicate-up)
'''

[[plugins]]
repo = 'vim-scripts/Align'
on_cmd = ['Align']
hook_add = '''
vnoremap <silent> a> :Align =><CR>
vnoremap <silent> a= :Align =<CR>
'''

[[plugins]]
repo = 'kana/vim-textobj-user'
on_map = [['ox', 'i^', 'a^']]
hook_post_source = '''
" htmlタグとタグの間のテキストをオブジェクト化する
call textobj#user#plugin('html', {
\   'text': {
\     'pattern': ['>', '<'],
\     'select-a': 'a^',
\     'select-i': 'i^',
\   },
\ })
'''

[[plugins]]
repo = 'kana/vim-textobj-indent'
depends = 'vim-textobj-user'
on_map = [['ox', 'ii', 'ai', 'iI', 'aI']]

[[plugins]]
repo = 'kana/vim-textobj-line'
depends = 'vim-textobj-user'
on_map = [['ox', 'il', 'al']]

[[plugins]]
repo = 'sgur/vim-textobj-parameter'
depends = 'vim-textobj-user'
on_map = [['ox', 'i,', 'a,']]

[[plugins]]
repo =  'haya14busa/incsearch.vim'
on_map = ['<Plug>']
hook_add = '''
map /  <Plug>(incsearch-forward)
'''

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
depends = 'ctrlp-py-matcher'
on_cmd = ['CtrlP']
hook_add = '''
nnoremap <silent> ,p :<C-u>CtrlP<CR>
let g:ctrlp_map = '<Nop>'

let g:ctrlp_max_files = 0
let g:ctrlp_lazy_update = 10
let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden --ignore .git --ignore .svn --ignore .hg --ignore .DS_Store --ignore "**/*.pyc" -g ""'
let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }
'''

[[plugins]]
repo = 'FelikZ/ctrlp-py-matcher'
on_source = 'ctrlp.vim'

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = ['TagbarToggle']
hook_add = '''
nnoremap <silent> ,tb :TagbarToggle<CR>
'''

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
on_ft = ['go', 'php', 'python', 'javascript', 'html', 'css', 'sass', 'scss']
hook_source = '''
nmap ,j :SplitjoinJoin<cr>
nmap ,s :SplitjoinSplit<cr>
'''

[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = ['GundoToggle']
hook_add = '''
nnoremap <silent> ,gu :GundoToggle<CR>
'''
