#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
from subprocess import Popen, PIPE

FILE_NAME = "SAFETY_AMEND_CHECK_HEAD"

def git(cmd):
    out, err = Popen("git "+cmd, shell=True, stdout=PIPE, stderr=PIPE, stdin=PIPE).communicate()
    if err:
        return ""

    return out.decode()[:-1]

try:
    f = open(FILE_NAME)
    old_head = f.read()
    f.close()
except:
    sys.exit(0)

os.remove(FILE_NAME)

head, prev_head = git("rev-list -n 2 HEAD").split("\n")

if old_head != prev_head:
    err_msg = "[Warning] detect unsafe commit --amend.\n" + \
    "%s commit already has been pushed to remote repository.\n" % old_head[:7] + \
    "you should execute the following command\n\n" + \
    "git reset %s\n\n" % old_head
    sys.stderr.write(err_msg)
