#!/usr/bin/env python

"""
pre-rebase hook

show warning message if "rebase" contains commits
that has already been pushed to remote branch.
"""

import sys
from commands import getoutput

base_branch = sys.argv[1]
if len(sys.argv) > 2:
    topic_branch = sys.argv[2]
else:
    topic_branch = "HEAD"

target_shas = getoutput("git rev-list %s..%s" % (base_branch, topic_branch)).split("\n")
remote_refs = map(lambda s: s.strip(), getoutput("git branch -r").split("\n"))

for sha in target_shas:
    for ref in remote_refs:
        pushed_shas = getoutput("git rev-list ^%s^@ refs/remotes/%s" % (sha, ref))
        if sha in pushed_shas.split("\n"):
            print(getoutput("git log %s -n 1 --oneline" % sha))
            print("has already been pushed to %s\n" % ref)
            while True:
                result = raw_input("continue ? (y/[n]) : ")
                if result in ["yes", "y"]:
                    sys.exit(0)
                elif result in ["no", "n", ""]:
                    sys.exit(1)

