#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
from subprocess import Popen, PIPE

FILE_NAME = "SAFETY_AMEND_CHECK_HEAD"

def git(cmd):
    out, err = Popen("git "+cmd, shell=True, stdout=PIPE, stderr=PIPE, stdin=PIPE).communicate()
    if err:
        return ""

    return out.decode()[:-1]

head = git("rev-list -n 1 HEAD")
remote_refs = map(lambda s: s.strip(), git("branch -r").split("\n"))

for ref in remote_refs:
    pushed_shas = git("rev-list ^%s^@ refs/remotes/%s" % (head, ref))
    if head in pushed_shas.split("\n"):
        break
else:
    # if HEAD is only local commit, don't write file."
    sys.exit(0)

f = open(FILE_NAME, "w")
f.write(head)
f.close()
