[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sainnhe/sonokai'
hook_add = '''
let g:sonokai_style = 'default'
let g:sonokai_disable_italic_comment = 1
let g:sonokai_diagnostic_text_highlight = 1
let g:sonokai_diagnostic_virtual_text = 'colored'
let g:sonokai_better_performance = 1

au MyAutoCmd VimEnter * nested colorscheme sonokai
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'numToStr/Comment.nvim'
hook_add = '''
lua require('Comment').setup()
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
nmap <silent> <leader>aj :ALENext<cr>
nmap <silent> <leader>ak :ALEPrevious<cr>

let g:ale_disable_lsp = 1

let g:ale_sign_error = "\uf05e"
let g:ale_sign_warning = "\uf071"
let g:ale_sign_column_always = 1

let g:ale_set_loclist = 0
let g:ale_set_quickfix = 0
let g:ale_open_list = 0
let g:ale_keep_list_window_open = 0

let g:ale_lint_on_enter = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_linters = {
\   'go': ['golint', 'govet', 'golangci-lint'],
\   'css': ['prettier', 'stylelint'],
\   'scss': ['prettier', 'stylelint'],
\   'json': ['jq'],
\   'javascript': ['prettier', 'eslint'],
\   'typescript': ['prettier', 'eslint'],
\   'vue': ['prettier', 'eslint', 'stylelint']
\ }

let g:ale_fix_on_save = 1
let g:ale_fixers = {
\   'dart': ['dart-format'],
\   'go': ['goimports'],
\   'css': ['prettier', 'stylelint'],
\   'scss': ['prettier', 'stylelint'],
\   'json': ['jq'],
\   'javascript': ['prettier', 'eslint'],
\   'typescript': ['prettier', 'eslint'],
\   'vue': ['prettier', 'eslint', 'stylelint']
\}

let g:ale_dart_format_options = '--line-length 140'
let g:ale_go_golangci_lint_options = ''
'''

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'andymass/vim-matchup'
hook_add = '''
let g:loaded_matchparen = 1
'''

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'goolord/alpha-nvim'
depends = 'nvim-web-devicons'
hook_add = '''
lua require'alpha'.setup(require'alpha.themes.startify'.config)
'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['plenary.nvim']
hook_add = '''
nnoremap ,p  <cmd>Telescope find_files find_command=rg,--no-ignore-dot,--hidden,-g,!.git/,--files<cr>
nnoremap ,ff <cmd>Telescope find_files find_command=rg,--no-ignore-dot,--hidden,-g,!.git/,--files<cr>
nnoremap ,fm <cmd>Telescope frecency<cr>
nnoremap ,fo <cmd>Telescope oldfiles<cr>
nnoremap ,fg <cmd>Telescope live_grep<cr>
nnoremap ,fG <cmd>Telescope grep_string<cr>
nnoremap ,fb <cmd>Telescope buffers<cr>
nnoremap ,fh <cmd>Telescope help_tags<cr>
nnoremap ,fc <cmd>Telescope command_history<cr>
nnoremap ,fk <cmd>Telescope keymaps<cr>

nnoremap ,<C-g><C-s> <cmd>Telescope git_status<cr>

lua require('rc/plugin-config/telescope')
'''

[[plugins]]
repo = 'tami5/sqlite.lua'

[[plugins]]
repo = 'nvim-telescope/telescope-frecency.nvim'
depends = ['telescope.nvim', 'sqlite.lua', 'nvim-web-devicons']
hook_add = '''
lua require('telescope').load_extension('frecency')
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
depends = 'nvim-web-devicons'
hook_add = '''
lua require('rc/plugin-config/lualine')
'''

[[plugins]]
repo = 'folke/which-key.nvim'
hook_add = '''
lua require("which-key").setup {}
'''

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
hook_add = '''
lua require('rc/plugin-config/gitsigns')
'''

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
hook_add = '''
lua require('colorizer').setup()
'''

[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'
hook_add = '''
lua require('rc/plugin-config/nvim-hlslens')
'''

[[plugins]]
repo = 'petertriho/nvim-scrollbar'
depends = ['nvim-hlslens', 'gitsigns.nvim']
hook_add = '''
lua require('rc/plugin-config/nvim-scrollbar')
'''

[[plugins]]
repo = 'rafamadriz/friendly-snippets'

[[plugins]]
repo = 'L3MON4D3/LuaSnip'
depends = 'friendly-snippets'
hook_add = '''
lua require("luasnip.loaders.from_vscode").lazy_load()
'''

[[plugins]]
repo = 'onsails/lspkind.nvim'

[[plugins]]
repo = 'hrsh7th/nvim-cmp'
depends = ['LuaSnip', 'lspkind.nvim']
hook_add = '''
lua require('rc/plugin-config/nvim-cmp')
'''

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
depends = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
depends = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
depends = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
depends = 'nvim-cmp'

[[plugins]]
repo = 'saadparwaiz1/cmp_luasnip'
depends = 'nvim-cmp'

[[plugins]]
repo = 'tzachar/cmp-tabnine'
depends = 'nvim-cmp'
build = './install.sh'

[[plugins]]
repo = 'octaltree/cmp-look'
depends = 'nvim-cmp'

[[plugins]]
repo = 'williamboman/mason.nvim'
hook_add = '''
lua require('rc/plugin-config/mason')
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
hook_add = '''
lua require('rc/plugin-config/mason-lspconfig')
'''

[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['mason.nvim', 'mason-lspconfig.nvim', 'cmp-nvim-lsp']
hook_add = '''
lua require('rc/plugin-config/nvim-lspconfig')
'''

[[plugins]]
repo = 'ray-x/lsp_signature.nvim'
hook_add = '''
lua require('lsp_signature').setup()
'''

[[plugins]]
repo = 'folke/lsp-colors.nvim'

[[plugins]]
repo = 'tami5/lspsaga.nvim'
depends = 'lsp-colors.nvim'
hook_add = '''
nnoremap <silent>,e <cmd>Lspsaga show_line_diagnostics<cr>
nnoremap <silent> [e <cmd>Lspsaga diagnostic_jump_prev<CR>
nnoremap <silent> ]e <cmd>Lspsaga diagnostic_jump_next<CR>

nnoremap <silent> ,rn <cmd>Lspsaga rename<CR>

nnoremap <silent> gh <cmd>lua require('lspsaga.provider').lsp_finder()<CR>

nnoremap <silent>,ca <cmd>Lspsaga code_action<CR>
vnoremap <silent>,ca :<C-u>Lspsaga range_code_action<CR>

nnoremap <silent> K <cmd>Lspsaga hover_doc<cr>
nnoremap <silent> ? <cmd>Lspsaga signature_help<cr>

nnoremap <silent> <C-u> <cmd>lua require('lspsaga.action').smart_scroll_with_saga(-1)<CR>
nnoremap <silent> <C-d> <cmd>lua require('lspsaga.action').smart_scroll_with_saga(1)<CR>

lua require('rc/plugin-config/lspsaga')
'''

[[plugins]]
repo = 'j-hui/fidget.nvim'
hook_add = '''
lua require('fidget').setup{}
'''

[[plugins]]
repo = 'noib3/nvim-cokeline'
depends = 'nvim-web-devicons'
hook_add = '''
lua require('rc/plugin-config/nvim-cokeline')
'''

[[plugins]]
repo = 'stevearc/stickybuf.nvim'
hook_add = '''
lua require('rc/plugin-config/stickybuf')
'''

[[plugins]]
repo = 'NMAC427/guess-indent.nvim'
hook_add = '''
lua require('guess-indent').setup {}
'''
