#----------------------------------------
# anyenv
# https://github.com/riywo/anyenv
#----------------------------------------

if [ -d $HOME/.anyenv  ] ; then
    export PATH="$HOME/.anyenv/bin:$PATH"
    eval "$(anyenv init -)"
    for D in `ls $HOME/.anyenv/envs`
    do
        export PATH="$HOME/.anyenv/envs/$D/shims:$PATH"
    done
fi

eval "$(pyenv virtualenv-init -)"
