#----------------------------------------
# anyenv
# https://github.com/riywo/anyenv
#----------------------------------------

if [ -d $HOME/.anyenv  ] ; then
    export PATH="$HOME/.anyenv/bin:$PATH"
    eval "$(anyenv init -)"
fi

# pyenv
eval "$(pyenv virtualenv-init -)"
