#----------------------------------------
# path settings
#----------------------------------------

## 重複したパスを登録しない。
typeset -U path

path=(
      $HOME/bin(N-/)
      $HOME/local/bin(N-/)
      /opt/local/bin(N-/)
      /usr/local/bin(N-/)
      /usr/bin(N-/)
      /bin(N-/)
      /sbin(N-/)
      /usr/local/sbin(N-/)
      /opt/local/sbin(N-/)
      /usr/sbin(N-/)
      /usr/pkg/sbin(N-/)
      $path
     )

#----------------------------------------
# man path settings
#----------------------------------------
## 重複したパスを登録しない。
typeset -U manpath

manpath=(
         $HOME/local/share/man(N-/)
         /opt/local/share/man(N-/)
         /usr/local/share/man(N-/)
         /usr/share/man(N-/)
        )

#----------------------------------------
# basic settings
#----------------------------------------

export TERM=xterm-256color
export XDG_CONFIG_HOME=$HOME/.config
export EDITOR=vim

#----------------------------------------
# language
#----------------------------------------

export LANG=en_US.UTF-8
export LC_ALL=$LANG

#----------------------------------------
# pager
#----------------------------------------

if type lv > /dev/null 2>&1; then
    ## lvを優先する。
    export PAGER="lv"
else
    ## lvがなかったらlessを使う。
    export PAGER="less"
fi

# lvの設定
export LV="-c -l"

# lessの設定
## -R: ANSIエスケープシーケンスのみ素通しする。
## 2012-09-04
export LESS="-R"

#----------------------------------------
# other
#----------------------------------------

# git
export PATH=$PATH:/usr/local/share/git-core/contrib/diff-highlight
