#--------------------------------------------------------------------------------
# path
#--------------------------------------------------------------------------------

#----------------------------------------
# path settings
#----------------------------------------

## 重複したパスを登録しない。
typeset -U path

path=(
      $HOME/bin(N-/)
      $HOME/local/bin(N-/)
      /opt/local/bin(N-/)
      /usr/local/bin(N-/)
      /usr/bin(N-/)
      /bin(N-/)
      /sbin(N-/)
      /usr/local/sbin(N-/)
      /opt/local/sbin(N-/)
      /usr/sbin(N-/)
      /usr/pkg/sbin(N-/)
      $path
     )

#----------------------------------------
# man path settings
#----------------------------------------
## 重複したパスを登録しない。
typeset -U manpath

manpath=(
         $HOME/local/share/man(N-/)
         /opt/local/share/man(N-/)
         /usr/local/share/man(N-/)
         /usr/share/man(N-/)
        )

#--------------------------------------------------------------------------------
# other
#--------------------------------------------------------------------------------

export TERM=xterm-256color
export XDG_CONFIG_HOME=$HOME/.config

#----------------------------------------
# language
#----------------------------------------

export LANG=en_US.UTF-8
export LC_ALL=$LANG

#----------------------------------------
# pager settings
#----------------------------------------

# ページャの設定
if type lv > /dev/null 2>&1; then
    ## lvを優先する。
    export PAGER="lv"
else
    ## lvがなかったらlessを使う。
    export PAGER="less"
fi

# lvの設定
export LV="-c -l"

if [ "$PAGER" != "lv" ]; then
    ## lvがなくてもlvでページャーを起動する。
    alias lv="$PAGER"
fi

# lessの設定
## -R: ANSIエスケープシーケンスのみ素通しする。
## 2012-09-04
export LESS="-R"

case ${OSTYPE} in
darwin*)
if command -v /usr/local/bin/src-hilite-lesspipe.sh > /dev/null; then
    export LESSOPEN='| /usr/local/bin/src-hilite-lesspipe.sh %s'
    function lvc() { if [ -f $1 ]; then less $1 | lv -c; fi;  }
fi
;;
linux*)
if command -v /usr/share/source-highlight/src-hilite-lesspipe.sh > /dev/null; then
    export LESSOPEN='| /usr/share/source-highlight/src-hilite-lesspipe.sh %s'
    function lvc() { if [ -f $1 ]; then less $1 | lv -c; fi;  }
fi
;;
esac

#----------------------------------------
# editor
#----------------------------------------

export EDITOR=vim
## vimがなくてもvimでviを起動する。
if ! type vim > /dev/null 2>&1; then
    alias vim=vi
fi

#----------------------------------------
# git pager
#----------------------------------------

if command -v diff-highlight > /dev/null && command -v nkf > /dev/null; then
    export GIT_PAGER='diff-highlight | nkf -w | less -R'
elif command -v lv > /dev/null; then
    export GIT_PAGER='lv -c'
fi
